
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: lms-keycloak
    environment:
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - ./src/main/resources/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - "start-dev"
      - --http-relative-path=/auth
      - --import-realm
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: postgres:16-alpine
    container_name: akseleu-keycloak-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2345:5432"
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16-alpine
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-service:
    image: quay.io/minio/minio:latest
    container_name: minio-service-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: akseleu
      MINIO_ROOT_PASSWORD: akseleu123
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio-service
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio-service:9000 akseleu akseleu123) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb myminio/dev-bucket || true;
      exit 0;
      "
  minio-db:
    image: postgres:16-alpine
    container_name: minio-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  lms-app:
    build: .
    container_name: lms-main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: 'true'
      MINIO_URL: http://minio-service:9000
      MINIO_USER: akseleu
      MINIO_PASSWORD: akseleu123
      MINIO_BUCKET: dev-bucket
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/auth/realms/lms-realm
    depends_on:
      postgres:
        condition: service_healthy
      minio-db:
        condition: service_healthy
      minio-service:
        condition: service_started
      keycloak:
        condition: service_started


volumes:
    postgres_data:
    keycloak_pg_data: