server:
  port: 8080

spring:
  application:
    name: LMS
  datasource:
    url: jdbc:postgresql://localhost:5442/lms_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/lms-realm

keycloak:
  realm: lms-realm
  auth-server-url: http://localhost:8081/auth
  client-id: lms-client
  client-secret: secret
  admin-username: admin
  admin-password: admin

minio:
    url: http://localhost:9000
    user: akseleu
    password: akseleu123
    bucket: dev-bucket